// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCompanionImageAsBase64(arg1, arg2) {
  return window['go']['handlers']['Companion']['GetCompanionImageAsBase64'](arg1, arg2);
}

export function GetCompanions() {
  return window['go']['handlers']['Companion']['GetCompanions']();
}
