// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetCompanionImageAsBase64(arg1:string,arg2:string):Promise<string>;

export function GetCompanions():Promise<Array<services.Companion>>;
