// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ConnectWifi(arg1:string):Promise<void>;

export function GetBrightness():Promise<number>;

export function GetVolume():Promise<number>;

export function GetWifiNetworks():Promise<Array<dto.WifiNetwork>>;

export function SetBrightness(arg1:number):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;
