// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function GetContainers():Promise<Array<handlers.ContainerStat>>;

export function Startup(arg1:context.Context):Promise<void>;
