// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWifi(arg1) {
  return window['go']['handlers']['ControlCenterHandler']['ConnectWifi'](arg1);
}

export function GetBrightness() {
  return window['go']['handlers']['ControlCenterHandler']['GetBrightness']();
}

export function GetVolume() {
  return window['go']['handlers']['ControlCenterHandler']['GetVolume']();
}

export function GetWifiNetworks() {
  return window['go']['handlers']['ControlCenterHandler']['GetWifiNetworks']();
}

export function SetBrightness(arg1) {
  return window['go']['handlers']['ControlCenterHandler']['SetBrightness'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['handlers']['ControlCenterHandler']['SetVolume'](arg1);
}
