// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContainers() {
  return window['go']['handlers']['Container']['GetContainers']();
}

export function Startup(arg1) {
  return window['go']['handlers']['Container']['Startup'](arg1);
}
