// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWifi(arg1) {
  return window['go']['handlers']['ControlHandler']['ConnectWifi'](arg1);
}

export function GetBrightness() {
  return window['go']['handlers']['ControlHandler']['GetBrightness']();
}

export function GetVolume() {
  return window['go']['handlers']['ControlHandler']['GetVolume']();
}

export function GetWifiNetworks() {
  return window['go']['handlers']['ControlHandler']['GetWifiNetworks']();
}

export function SetBrightness(arg1) {
  return window['go']['handlers']['ControlHandler']['SetBrightness'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['handlers']['ControlHandler']['SetVolume'](arg1);
}
