// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApp() {
  return window['go']['handlers']['Launcher']['AddApp']();
}

export function GetApps() {
  return window['go']['handlers']['Launcher']['GetApps']();
}

export function LaunchApp(arg1) {
  return window['go']['handlers']['Launcher']['LaunchApp'](arg1);
}

export function RemoveApp(arg1) {
  return window['go']['handlers']['Launcher']['RemoveApp'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['Launcher']['Startup'](arg1);
}
