// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function AddApp():Promise<handlers.AppFrontend>;

export function GetApps():Promise<Array<handlers.AppFrontend>>;

export function LaunchApp(arg1:string):Promise<void>;

export function RemoveApp(arg1:string):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
