// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLyrics(arg1, arg2) {
  return window['go']['handlers']['Lyrics']['GetLyrics'](arg1, arg2);
}
