// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerStats() {
  return window['go']['handlers']['Server']['GetServerStats']();
}

export function Startup(arg1) {
  return window['go']['handlers']['Server']['Startup'](arg1);
}
