// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBattery() {
  return window['go']['handlers']['SystemHandler']['GetBattery']();
}

export function GetConfig() {
  return window['go']['handlers']['SystemHandler']['GetConfig']();
}

export function GetVolume() {
  return window['go']['handlers']['SystemHandler']['GetVolume']();
}

export function GetWifi() {
  return window['go']['handlers']['SystemHandler']['GetWifi']();
}

export function OpenNotifications() {
  return window['go']['handlers']['SystemHandler']['OpenNotifications']();
}

export function SwitchWorkspace(arg1) {
  return window['go']['handlers']['SystemHandler']['SwitchWorkspace'](arg1);
}
