// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBattery() {
  return window['go']['handlers']['SystemHandler']['GetBattery']();
}

export function GetConfig() {
  return window['go']['handlers']['SystemHandler']['GetConfig']();
}

export function GetTheme() {
  return window['go']['handlers']['SystemHandler']['GetTheme']();
}

export function GetVolume() {
  return window['go']['handlers']['SystemHandler']['GetVolume']();
}

export function GetWifi() {
  return window['go']['handlers']['SystemHandler']['GetWifi']();
}

export function OpenNotifications() {
  return window['go']['handlers']['SystemHandler']['OpenNotifications']();
}

export function Restart() {
  return window['go']['handlers']['SystemHandler']['Restart']();
}

export function Shutdown() {
  return window['go']['handlers']['SystemHandler']['Shutdown']();
}

export function Sleep() {
  return window['go']['handlers']['SystemHandler']['Sleep']();
}

export function SwitchWorkspace(arg1) {
  return window['go']['handlers']['SystemHandler']['SwitchWorkspace'](arg1);
}
