// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetBattery():Promise<dto.BatteryData>;

export function GetConfig():Promise<dto.Config>;

export function GetTheme():Promise<dto.Theme>;

export function GetThemes():Promise<Array<string>>;

export function GetVolume():Promise<dto.VolumeData>;

export function GetWeather():Promise<dto.WeatherData>;

export function GetWifi():Promise<dto.WifiData>;

export function OpenNotifications():Promise<void>;

export function Restart():Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function Sleep():Promise<void>;

export function SwitchWorkspace(arg1:number):Promise<void>;
