// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LaunchTerminal() {
  return window['go']['handlers']['Terminal']['LaunchTerminal']();
}
