// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExpandWindow() {
  return window['go']['main']['App']['ExpandWindow']();
}

export function ShrinkWindow() {
  return window['go']['main']['App']['ShrinkWindow']();
}
