// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExpandWindow():Promise<void>;

export function ShrinkWindow():Promise<void>;
