// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExpandWindow() {
  return window['go']['main']['App']['ExpandWindow']();
}

export function HasConfig() {
  return window['go']['main']['App']['HasConfig']();
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}

export function ShrinkWindow() {
  return window['go']['main']['App']['ShrinkWindow']();
}
